// good-roots/Modern Restaurant Landing Page/src/components/FoodRevolution.tsx
export function FoodRevolution() {
  return (
    <section className="py-24 px-6 md:px-16 lg:px-24 bg-white">
      <div className="max-w-7xl mx-auto">
        <h2 style={{ fontSize: 'clamp(2.5rem, 6vw, 5rem)', fontWeight: 900, lineHeight: 1, letterSpacing: '-0.02em', color: 'var(--soft-black)' }}>
          REAL FOOD<br />REVOLUTION.
        </h2>
      </div>
    </section>
  );
}

// good-roots/src/components/FoodRevolution.vue
<template>
  <section class="py-24 px-6 md:px-16 lg:px-24 bg-white">
    <div class="max-w-7xl mx-auto">
      <h2 style="font-size: clamp(2.5rem, 6vw, 5rem); font-weight: 900; line-height: 1; letter-spacing: -0.02em; color: var(--soft-black)">
        REAL FOOD<br />REVOLUTION.
      </h2>
    </div>
  </section>
</template>

<script>
export default {
  name: 'FoodRevolution'
}
</script>
